name: Mirror commits on main branch

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  mirror-main:
    uses: ./.github/workflows/mirror.yml
    with:
      branch: main
    secrets:
      TECHRIDER_SSH_PUBLIC_KEY: ${{ secrets.TECHRIDER_SSH_PUBLIC_KEY }}
      TECHRIDER_SSH_PRIVATE_KEY: ${{ secrets.TECHRIDER_SSH_PRIVATE_KEY }}
