// IMPORTANT: This file is automatically generated by createReferenceScriptUtxo script, do not edit it manually
import type {RefTxIn} from '@meshsdk/core'

export const preprodPoolRefScriptUtxo: RefTxIn = {
  txHash: 'c5e6edd72adee1748b95f9adfcc0f66a5d680bda088fa26c59623b63b7631eaa',
  txIndex: 0,
  scriptSize: 3172,
}
