// IMPORTANT: This file is automatically generated by createReferenceScriptUtxo script, do not edit it manually
import type {RefTxIn} from '@meshsdk/core'

export const preprodPoolRefScriptUtxo: RefTxIn = {
  txHash: '5265d2dc1e8cde106e7ab7e55db5ef271a54d473d577a7c2d9388053e8b82aff',
  txIndex: 0,
  scriptSize: 3174,
}
