// IMPORTANT: This file is automatically generated by createReferenceScriptUtxo script, do not edit it manually
import type {RefTxIn} from '@meshsdk/core'

export const preprodPoolRefScriptUtxo: RefTxIn = {
  txHash: 'fd647d580c66a3d046e687c581db421e933d9c3d7b5853cf03d1693e77ad0578',
  txIndex: 0,
  scriptSize: 3014,
}
